version: '3.9'

services:
  go-app:
    container_name: go-app
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - go_db
      - redis # The go-app now depends on the redis service
    volumes:
      - .:/app
      - go_mod_cache:/go/pkg/mod
    environment:
      DB_HOST: go_db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_REDIRECT_URL: http://localhost:8080/api/v1/auth/callback
      REDIS_HOST: redis # New environment variable for Redis host
      REDIS_PORT: 6379 # New environment variable for Redis port
      SESSION_SECRET: your-very-long-secret-key # New secret key for signing session cookies
      
  go_db:
    container_name: go_db
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:8
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data # A new volume to persist Redis data

volumes:
  pgdata:
  go_mod_cache:
  redis_data: # A new volume for Redis data persistence
