version: '3.9'

services:
  go-app:
    container_name: go-app
    image: abc/go-app:1.0.0
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - go_db
    volumes:
      - .:/app         # Mount code for hot reload
      - go_mod_cache:/go/pkg/mod  # Optional: speeds up rebuilds
    environment:
      DB_HOST: go_db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_REDIRECT_URL: http://localhost:8080/api/v1/auth/callback

  go_db:
    container_name: go_db
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  go_mod_cache:
