basePath: /api/v1
host: localhost:8080
info:
  contact: {}
  description: A demo of OAuth2 login with Google using Gin and Swagger
  title: OAuth2 API
  version: "1.0"
paths:
  /api/v1/auth/callback:
    get:
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Callback from Google OAuth
      tags:
      - Auth
  /api/v1/auth/login:
    get:
      responses:
        "302":
          description: redirect to Google
          schema:
            type: string
      summary: Login with Google
      tags:
      - Auth
swagger: "2.0"
